### ISSUE TITLE
Adding postgresql relation fails

### ISSUE THREAD

**Issue by mthaddon** [juju/hello-juju-charm#1]
In https://juju.is/docs/getting-started-with-juju you're instructed to add a postgresql relation, but doing so gives the following error:
```
machine-0: 10:09:57 INFO unit.hello-juju/0.juju-log db:2: Invoking reactive handler: reactive/hello_juju.py:91:create_and_configure_database
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed Traceback (most recent call last):
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/current/init.py", line 3, in <module>
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     hello_juju.db.create_all()
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/venv/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 1039, in create_all
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     self._execute_for_all_tables(app, bind, 'create_all')
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/venv/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 1031, in _execute_for_all_tables
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     op(bind=self.get_engine(app, bind), **extra)
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/venv/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 4554, in create_all
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2094, in _run_visitor
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     with self._optional_conn_ctx_manager(connection) as conn:
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     return next(self.gen)
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2086, in _optional_conn_ctx_manager
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     with self._contextual_connect() as conn:
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2302, in _contextual_connect
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     self._wrap_pool_connect(self.pool.connect, None),
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     return fn()
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 364, in connect
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     return _ConnectionFairy._checkout(self)
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     fairy = _ConnectionRecord.checkout(pool)
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     rec = pool._do_get()
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/venv/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     self._dec_overflow()
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     with_traceback=exc_tb,
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     raise exception
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/venv/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     return self._create_connection()
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     return _ConnectionRecord(self)
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     self.__connect(first_connect_check=True)
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/venv/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     ).exec_once_unless_exception(self.connection, self)
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/venv/lib/python3.6/site-packages/sqlalchemy/event/attr.py", line 314, in exec_once_unless_exception
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     self._exec_once_impl(True, *args, **kw)
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/venv/lib/python3.6/site-packages/sqlalchemy/event/attr.py", line 285, in _exec_once_impl
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     self(*args, **kw)
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/venv/lib/python3.6/site-packages/sqlalchemy/event/attr.py", line 322, in __call__
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     fn(*args, **kw)
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 1406, in go
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     return once_fn(*arg, **kw)
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/venv/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 199, in first_connect
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     dialect.initialize(c)
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/venv/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/pg8000.py", line 215, in initialize
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     super(PGDialect_pg8000, self).initialize(connection)
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/venv/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py", line 2624, in initialize
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     super(PGDialect, self).initialize(connection)
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 313, in initialize
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     connection
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/venv/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/base.py", line 2869, in _get_server_version_info
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     v = connection.execute("select version()").scalar()
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1003, in execute
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     return self._execute_text(object_, multiparams, params)
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1178, in _execute_text
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     parameters,
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     e, statement, parameters, cursor, context
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1514, in _handle_dbapi_exception
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     util.raise_(exc_info[1], with_traceback=exc_info[2])
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     raise exception
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1294, in _execute_context
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     result = context._setup_crud_result_proxy()
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 1259, in _setup_crud_result_proxy
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     result = self.get_result_proxy()
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 1234, in get_result_proxy
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     return result.ResultProxy(self)
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/venv/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 775, in __init__
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     self._init_metadata()
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/venv/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 807, in _init_metadata
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     self._metadata = ResultMetaData(self, cursor_description)
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/venv/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 296, in __init__
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     textual_ordered,
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/venv/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 514, in _merge_cursor_description
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     ) in raw_iterator
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/venv/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 497, in <listcomp>
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     (
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/venv/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 621, in _merge_cols_by_none
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     ) in self._colnames_from_description(context, cursor_description):
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed   File "/srv/hello-juju/venv/lib/python3.6/site-packages/sqlalchemy/engine/result.py", line 545, in _colnames_from_description
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed     colname = description_decoder(colname)
unit-hello-juju-0: 10:09:58 WARNING unit.hello-juju/0.db-relation-changed TypeError: expected bytes, str found
machine-0: 10:09:58 ERROR unit.hello-juju/0.juju-log db:2: Hook error:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-hello-juju-0/.venv/lib/python3.6/site-packages/charms/reactive/__init__.py", line 74, in main
    bus.dispatch(restricted=restricted_mode)
  File "/var/lib/juju/agents/unit-hello-juju-0/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 390, in dispatch
    _invoke(other_handlers)
  File "/var/lib/juju/agents/unit-hello-juju-0/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 359, in _invoke
    handler.invoke()
  File "/var/lib/juju/agents/unit-hello-juju-0/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 181, in invoke
    self._action(*args)
  File "/var/lib/juju/agents/unit-hello-juju-0/charm/reactive/hello_juju.py", line 103, in create_and_configure_database
    create_database_tables()
  File "/var/lib/juju/agents/unit-hello-juju-0/charm/reactive/hello_juju.py", line 66, in create_database_tables
    check_call('sudo -u www-data /srv/hello-juju/venv/bin/python3 /srv/hello-juju/current/init.py'.split())
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo', '-u', 'www-data', '/srv/hello-juju/venv/bin/python3', '/srv/hello-juju/current/init.py']' returned non-zero exit status 1.
```

**Comment by manadart** [comment]
Out use of `subprocess.check_call` hides the real error here, which is actually this:
https://github.com/sqlalchemy/sqlalchemy/issues/5645

**Comment by jameinel** [comment]
So the actual error was in 'hello-juju' the application, not 'hello-juju-charm' the charm that was deploying it, but this should be fixed now.
